baseURL: https://hashbang0.com/
languageCode: en-gb
title: '#!0 - A Site of Life & Geekery'
theme: rehyde-x
author:
  name: Ben Lavery-Griffiths
outputs:
  home:
  - HTML
  - RSS
  - JSON
permalinks:
  post: /:year/:month/:day/:title/
taxonomies:
  category: categories
  tag: tags
params:
  email: ben@lavery-griffiths.com
  colorTheme: theme-base-0b
  fullWidth: true
  highlight: solarized-light
  home: Home
  truncate: true
  rss: true
  icons:
    iconSize: 2x
    iconList:
      - name: github
        link: https://github.com/forquare/
        isSquaredIcon: true
      - name: stack-overflow
        link: https://stackoverflow.com/users/389975/forquare
        isSquaredIcon: false
      - name: stack-exchange
        link: https://stackexchange.com/users/166079/forquare
        isSquaredIcon: false
      - name: mastodon
        link: https://hachyderm.io/@forquare
        isSquaredIcon: false
      - name: linkedin
        link: https://www.linkedin.com/in/benlavery/
        isSquaredIcon: false
      - name: email
        mailLink: ben@lavery-griffiths.com
        isSquaredIcon: true
      - name: rss
        isSquaredIcon: true
menu:
  main:
  - identifier: categories
    name: Categories
    url: /categories/
  - identifier: tags
    name: Tags
    url: /tags/
related:
  includeNewer: false
  indices:
  - name: keywords
    weight: 150
  - name: tags
    weight: 100
  threshold: 80
  toLower: true

