baseurl = "/"
languageCode = "en-gb"
disqusShortname = "hb0"
title = "#!0 - A Site of Life & Geekery"
theme = "rehyde-x"

[author]
	name = "Ben Lavery-Griffiths"

[permalinks]
	post = "/:year/:month/:day/:title/"

[taxonomies]
	category = "categories"

[params]
	truncate = false
	theme = "theme-base-0b"
	highlight = "sunburst"
	home = "Home"
#	
	github = "https://github.com/forquare/"
	stackOverflow = "https://stackoverflow.com/users/389975/forquare"
	stackExchange = "https://stackexchange.com/users/166079/forquare"
	linkedin = "https://www.linkedin.com/in/benlavery/"
	twitter = "https://twitter.com/forquare"
	email = "ben.lavery@hashbang0.com"
#
	rss = true

[params.social]
      iconSize = "2x"
      isSquaredIcon = true

[[menu.main]]
	name = "PGP Key"
	identifier = "pgp"
	url = "/pgp/"

[related]
	threshold = 80
	includeNewer = false
	toLower = true
	
[[related.indices]]
	name = "keywords"
	weight = 150
[[related.indices]]
	name  = "tags"
	weight = 100
