name: 'Publish Dev to Manaha'
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - 'dev/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4  #v2.7.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f  #v3.0.0
        with:
          hugo-version: 'latest'
          extended: true
      - name: Set timezone
        uses: MathRobin/timezone-action@089a978eb83af183f6225bbfc010df73e083d523  #v1.1
        with:
          timezoneLinux: "UTC"
      - name: Build Site
        run: |
          hugo --cleanDestinationDir --enableGitInfo --minify --baseURL="https://dev.hashbang0.com/" --buildFuture --buildDrafts --ignoreCache --logLevel info
          date >> ./public/build_date.txt
      - name: Deploy with rsync
        run: rsync -avz --omit-dir-times -e "ssh -p ${{ secrets.SSH_PORT }}" ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_BASE_PATH }}/dev_hashbang0/
